### ISSUE TITLE
Search by island/region instead of city

### ISSUE THREAD

**Issue by danielbenjamins** [cermak-petr/actor-booking-hotels-2#3]
I just found out about Apify and I'm experimenting with this actor. It seems very promising but I have a question how to get the results of an area/region instead of a city.

For example, when I set "Texel" (an island) as the Booking search query it only looks up hotels in "De Koog", which is a city on the island. So basically it's not searching for "Texel" (my input) but for, I guess, the largest city?

This way only 70 accommodations show up, while there are 184 total accommodations on the whole island. Is there any way I can get around this?

URL that the actor is using:
https://www.booking.com/searchresults.html?dest_type=city;ss=Texel&order=bayesian_review_score&selected_currency=EUR&changed_currency=1&top_currency=1&lang=nl&group_adults=2&no_rooms=1&rows=20

When I do a manual search for "Texel":
https://www.booking.com/searchresults.nl.html?label=gen173nr-1DCAQoggI46wdIHFgEaCeIAQGYARy4AQfIAQzYAQPoAQH4AQOIAgGoAgO4AsnZxOQFwAIB&lang=nl&sid=f75734378f3e09bdaeb560c3f1961ce2&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.nl.html%3Flabel%3Dgen173nr-1DCAQoggI46wdIHFgEaCeIAQGYARy4AQfIAQzYAQPoAQH4AQOIAgGoAgO4AsnZxOQFwAIB%3Bsid%3Df75734378f3e09bdaeb560c3f1961ce2%3Bsb_price_type%3Dtotal%3Bsrpvid%3D0f7c7de49f7b0018%26%3B&ss=Texel%2C+Nederland&is_ski_area=0&checkin_year=&checkin_month=&checkout_year=&checkout_month=&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1&ss_raw=texel&ac_position=0&ac_langcode=nl&ac_click_type=b&dest_id=1023&dest_type=region&place_id_lat=53.093818&place_id_lon=4.799851&search_pageview_id=d4147dea73650308&search_selected=true

**Comment by cermak-petr** [comment]
New "destType" attribute was added to the INPUT. 
Currently available values are "city" and "region".
If you know about any other types, let me know, I can add them too.

**Comment by danielbenjamins** [comment]
Thanks! Although I'm still struggling to get all the results that are available. I tried many variations (city, region, different start URLs, etc.)

I have another example, please see https://www.booking.com/searchresults.nl.html?region=1020 and screenshot. When you click on the link, there are 48 properties found. When I try the actor, I only get about 14-16 results. Is there anything else that I could/should try?

I just need the property information, it doesn't matter if there's availability. Also number of people ,travel dates, number of rooms, etc. is not what I need. So even if a property is not available at a given time, and is still listed on Booking, I would like that result. So I would like to get all same 48 results as if I do a manual search on Booking.com.

Is this possible?

<img width="796" alt="Screen Shot 2019-04-03 at 11 47 21" src="https://user-images.githubusercontent.com/985981/55493610-455d1a00-5607-11e9-9f38-95206fcc1903.png">
